sudo: required
language: java
jdk:
- openjdk8
services:
- docker
- postgresql
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "fu1HG5B5obr/wN907CviMge+jnxjRbwZ9AlecJNIdw3hOZiFLS81mlGu2e5NVEEz0qIRp9ZR40CNZm+sKAjrAnOHA/jVTqGbMUiHR1XzBg5gwXQXtbhhGr2tkKGkwcYyDl7BGnx4le5Op/AQQFkrQc3dSFLA/17h/YL0mLY7dr910oYxQAUZH0HMJudl8qctU/+8mBo0wvsyihKrWrfcEVci/rFg7on7McBsJi4ggC8MSRyhgWGkRuw6dP0ff9+nyiGsWZfSePhh+TVuA3NUQWGipIaTT60uA/YC9h/PY3EDzvPFMhGr9yghCOcUNtuAhAtS97V+HfEiBfEBU7JIMbVGmcCc6i1IzrrmsM2jlfX83N0gpKH+9TI7iwKjoiyPa4nG6iPf3rx+T7Qy3ooTRcNJkYk98aqKfreNn5GrtcStEB6B4xhU4CskCR0jJiGUWCrL17jSrysJ8gRHSAw1Axc/bacu8VdoiXk5pflrbEbHWL8vbxNxnXV3nZS9VMYMzuvRaw0OuBeJDwR41OkHUsbOULVZua9FQpq21rv+5nA3D1e4vwmWvt/GEvnA8dk9O+3fn+/O4Vf7tcdScCIHNv0tTycQOLDpkPymDt6a47DHb8BtEY4X1e09GeWbhur4EUDsaiIRP7sxkzBpsPyt1hmBqR2I0AKSd5j/mBW5mXE="
  # AWS_SECRET_ACCESS_KEY
  - secure: "rKKBW7qrAcOeNw2xJtksxV7hU7Xjj4aQzGWdQO28FdoeSyIFqYp2rCRX07UoxERXC0a7qPvX5WuRPJBugHJyT1gPWR6L8qoT/62F+YzSIv+gwXVCQrc0v2sINeNHsYRHZ5br+Z1Dpt/jJ+CZPXqlN/VQmlGPC6QH5KN9lKr7IbSKnLTVS/cCuMM0d9lrZ/+OoPlJSz+XogOzE+m8NcBNAR08dK+xLqnvvGfhofYLYkWWbsvQ7BUeLgeaexcqPbYxjxAs83reY8rcL/L4pyxXbg99ux17rsY8xynNA9JLpyR+JkFu/rNNOKHrY7GVyUyvr+WWwTtSSnURktCjtWS36jpUJ/72446yuOnBMW52Pxcc2zy0KIfOtX08wSEL0A6SmslFUwA/qGVhkT9k2c8MgW9MTAggMOSwtdWJoAK6KAoeYDW7KrbqBO/V3jQbQ/P55L2A0ReSIhKIt0V/Zn/OHGKk2QGXiMd9sJW0/ObQzfwM0dAElR/ejhJHijSaN28NCUfe2DBjpwCeBP4a6eOJNl4b/SUspXNf/kPZp9sz49x/Jfk+UuUhTuo4nACzTy/mWfYYeAY7jyn9sx8wziPWydWj9u0HCuVzSZqCVP394aGAi/zBTt0jBiVy1VAZdeB7mdoVRRpPuDemTTAJYRg5D5pccoyepsklf10Mu9QxyvM="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="oma-opintopolku"

before_script:
  - psql -c "CREATE USER \"oph\" PASSWORD 'oph';" -U postgres
  - psql -c "CREATE DATABASE \"omaopintopolku\" OWNER 'oph';" -U postgres
  # regrettably, migrations require extensive rights:
  - psql -c "ALTER ROLE \"oph\" WITH superuser;" -U postgres

script:
- mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
- cp -v target/oma-opintopolku-*.jar $DOCKER_BUILD_DIR/artifact/oma-opintopolku.jar

- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
- provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
